# environment/conda_dependencies.yaml

name: custom-transformers-env # Reflects CUDA 12.4
channels:
  - conda-forge
  - defaults
dependencies:
  # --- Core Python ---
  - python=3.10

  # --- Pip ---
  - pip

  # --- Pip Packages ---
  - pip:
      # Install PyTorch using pip and index URL for specific CUDA build
      - torch==2.2.0
      # Core Azure ML dependency
      - azureml-inference-server-http

      # Transformers and ecosystem (use versions compatible with PT 2.6)
      - transformers==4.51.3 # Check latest compatible
      - accelerate==1.6.0  # Check latest compatible
      - numpy==1.26.4
      # - bitsandbytes==0.45.5 # Check BnB compatibility with PT 2.6 / CUDA 12.4

      # Tokenizer dependencies
      # - sentencepiece
      # - protobuf

      # Optional
      # - Pillow
      # - python-dotenv
      # - requests