# environment/environment.yml - UPDATED FOR DOCKER BUILD CONTEXT

$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: gemma3-custom-py311-pt26-cu124 # Keep the same target name
# version: 7

# --- Use Docker build context ---
build:
  path: . # Build context is the current directory (environment/)
  dockerfile_path: Dockerfile # Specify the Dockerfile name

# --- Optional: Description ---
description: Custom environment for Gemma 3 built via Dockerfile (py311/pt26/cu124).

# The 'image' and 'conda_file' properties are NOT used when 'build' is specified.