# environment/environment.yml
$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: pytorch251-on-acpt-base # Choose a new, descriptive name
version: 4                   # Start with version 1
description: Based on acpt-pytorch-2.2-cuda12.1, upgraded to PyTorch 2.5.1 (cu121) and project dependencies via pip.
build:
  path: . # Build context is the directory containing this YAML and the Dockerfile
  dockerfile_path: Dockerfile # The name of the Dockerfile you just created